### ISSUE TITLE
Cel-Shading Support

### ISSUE THREAD

**Issue by mecwerks** [zturtleman/spearmint#211]
Any plans for this?

I tried to port the patch from ioquake3 found [here](http://ioquake3.org/patchez/celshad3.patch). But it didn't really give a great looking effect.

**Comment by zturtleman** [comment]
That patch is in Turtle Arena 0.6. It has since removed because of the decision to use unmodified Spearmint. I ported it not understanding what it was but committed it anyway. That "cel shading" is image blurring. I don't plan to add global image blurring options to Spearmint. It would be better performance-wise to blur the assets ahead of time if that is going to be the game's art style. So for making a new "cel shaded" game it's no help, and to me it's not "cel shading" at all as it doesn't affect lighting...

Spearmint supports faked cel / toon shading (split light levels) used by ZEQ2-lite and Turtle Arena 0.6. It would be better using GLSL instead of altering the "cel shading" stage's texture coords, but it works fairly well. It requires being added to each shader that will use it. See "tcGen cel" on the [Shaders](https://github.com/zturtleman/spearmint/wiki/Shaders) wiki page.

"Cel outline" can probably be done by rendering a model twice, with the second time using a custom shader that has "cull back" and some vertex deform.

I'm not planning to add a new cvar that turns Quake 3 into a cel-shaded game.

**Comment by mecwerks** [comment]
alright thanks
