### ISSUE TITLE
Q3 Demo Test 1.09 support

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#221]
I would love to see the Quake 3 Demo Test with the additions/improvements in your engine. It's probably one of the finest Q3A engines around! The main resource folder path should probably be changed to either "demotestq3", "dtq3", or any other name you might think of. Here's the link to the demo test: 
https://mega.nz/#!R980yL7Z!CV0muwcioEWlDsFvxEJdcNCDtkxITtBbNkkjF89kpbo
Also, I would like to know how to be able to use the patch data for the demo version of Q3 in Spearmint.

**Comment by ensiform** [comment]
But the source for those old versions of Q3 aren't available hence why they aren't supported by ioquake3 either.

**Comment by zturtleman** [comment]
I have it set up as demoq3test, along with q3test-1.06, q3test-1.07, and q3test-1.08.

I'm currently not planning to make the mint-arena mod code better support Quake 3 test versions. More engine changes for supporting the data files (primarily BSPs and shaders) may happen.

Regarding using [spearmint-patch-data](https://github.com/zturtleman/spearmint-patch-data); set fs_cdpath to the directory with your game pk3s, fs_basepath to spearmint-patch-data path, and set sv_pure to 0. Copy or symlink Spearmint baseq3 `vm/mint-cgame.qvm` and `vm/mint-game.qvm` (compiled from [mint-arena](https://github.com/zturtleman/mint-arena) or copied out of spearmint pk3 in release downloads) to fs_cdpath, fs_basepath, or fs_homepath for each game you wish to run. Extract `models/players/sarge` and `sound/players/sarge` from quake3 into fallback-data (which is used by games such as q3test 1.06 to 1.08 that lack required Sarge player).

You can zip the spearmint patch data instead of running it out of the git checkout, which allows enabling sv_pure and not screwing with the file system paths. Don't zip description.txt but zip the rest of the files in the patch game directory plus the `vm/mint-cgame.qvm` and `vm/mint-game.qvm` files.

**Comment by coltongit** [comment]
Thanks for the heads up! Mind also doing 1.05 & 1.03 as well? Thanks in advance. Would love to use the bot AI from 1.05 in Spearmint! (even though it can only use the gauntlet/machinegun).

**Comment by zturtleman** [comment]
1.05 and 1.03 use a BSP format very different from retail Q3, which I wasn't able to figure out how to load. The q3test bots are handled different (there is no botfiles/ directory like demo / retail), so bots aren't usable using Spearmint + mint-arena.

**Comment by coltongit** [comment]
You could disassemble the main executables of each version, then work with that code to determine how the Q3Test 1.05 bots (and the bsp files) are handled/loaded. The IHV leak also has bots, but they just aimlessly go towards the wall.

**Comment by zturtleman** [comment]
uh, no.
