### ISSUE TITLE
Another bot issue in 17t6remix/17t6ctf

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#223]
There happens to be an issue with botplay in these 2 maps in which they get stuck in one portion of the floor (it's more evident in 17t6ctf). Happens even with the latest spearmint. ioquake3 does not seem to have this error.
17t6remix link:
http://lvlworld.com/review/id:1847
17t6ctf link:
https://ws.q3df.org/map/17t6ctf/
Botplay patch link:
https://mega.nz/#!F4tAmChI!oMWbHT6ZJBt2NbFJ70uhAjfMXZUbrbIpyAgUsu-mRWc
The reason for the patch is they wouldn't do anything without you shooting at them in both maps. With the patch, they'll go almost everywhere, but they're not able to grab the MH or LG for some reason.

**Comment by KuehnhammerTobias** [comment]
I did a quick check about this issue:
AFAIK, this is not directly related to AI game/engine code. The issue you encountered depends on the AAS file for those maps. The AAS file is the file bots use to navigate through the bsp world.
In some cases the map is built badly, this causes the bots to get stuck in 'solid areas'.
You can test this by starting a map in developer mode (/devmap mapname), and use the 'bot_testsolid'
command, entered into your console after the map is loaded.
If the map has spme 'solid areas' the console will print 'SOLID AREA' on your top left Corner.
See the screenshot below (taken from 17t6remix).
![17remix](https://cloud.githubusercontent.com/assets/5429387/15040727/1a391f04-12b7-11e6-81ec-8c126f860daa.jpg)

Your patch from above simply holds different AAS files.
NOTE: Care must be taken when creating AAS files for maps that were compiled with the -meta switch during the BSP Phase, in this case you MUST compile AAS files using the 'forcesidesvisible' Switch, otherwisse the AAS file will always be 'solid' (or not created at all).
Some more Basic instructions about 'Testing AAS files': https://icculus.org/gtkradiant/documentation/Compile_Manual/bspc.txt

**Comment by coltongit** [comment]
Never thought about that... I'll try & see if I can fix that with
another aas file (forcesidesvisible was already used).

**Comment by coltongit** [comment]
It doesn't seem to fix this with BSPC 2.1i. 2.1j might work. I'll also try 2.1h & 1.7 to see if they work as well.

**Comment by zturtleman** [comment]
You could try BSPC in the Spearmint repo as well. `make -C code/bspc`. Note that force sides visible and grapple reach are enabled by default.

**Comment by coltongit** [comment]
Maybe you might want to put the make command for bspc in the readme.md on github zturtleman.

**Comment by coltongit** [comment]
Spearmint BSPC does not fix this problem...

**Comment by KuehnhammerTobias** [comment]
I'm in doubt you'll fix this issue by using different bspc versions.
Remember, the problem is the map file, from which the bsp file was created from, NOT bspc or even game code.
Note: the review to this map already mentions that bots won't work properly: http://lvlworld.com/review/id:1847
So, you need the source file of the map to fix this issue..., the map file is owned by the author of the map.

**Comment by coltongit** [comment]
Either that, or the map can be decompiled and fixed just as easily
using the q3map2 from gtkradiant 1.6.5. 1.6.5's gtkradiant has texture
alignment support (to a degree).

**Comment by ensiform** [comment]
Decompiling the map trashes lighting, texture alignment and sometimes incorrect brushwork.  Its more work than you think.  And besides its not like its necessarily "legal".  The map's design in general is quite poor I think is the issue, no?

**Comment by coltongit** [comment]
Um, no. The latest q3map2 keeps lighting, brushwork, and texture alignment
(to a degree), as I specified earlier. I tried this myself, and I was able
to compile a decompiled map with lighting, brushwork, and texture alignment
all virtually the same as the original. Try it for yourself and PROVE IT
that I'm wrong.

**Comment by ensiform** [comment]
The 1.6.5 version isn't listed anywhere that I saw.  And point lights (classname "light" entity) cannot possibly be saved because they are removed from the bsp during compile unless flagged to not which most people don't do.  Shader lights of course will be there because the shaders are there when you recompile.

**Comment by coltongit** [comment]
It's on Quake3World. Just Google search "gtkradiant 1.6.5" & you'll find it.

**Comment by aisouard** [comment]
>I tried this myself, and I was able to compile a decompiled map with lighting, brushwork, and texture alignment all virtually the same as the original. Try it for yourself and PROVE IT that I'm wrong.

Please provide us the map you've successfully decompiled so we can take a look on it, I agree for the texture alignment since I remember using a q3map2 version coming from NetRadiant.

Regarding the lights, it's as @ensiform said, q3map2 removes the lights entities unless the author sets the parameter "_keeplights" to 1 inside the worldspawn entity.

**Comment by Mateos81** [comment]
Latest GtkRadiant:  https://s3.amazonaws.com/gtkradiant/GtkRadiant-1.6.5-20160424.zip

**Comment by mecwerks** [comment]
I think this issue should be closed due to it being a map specific bug. Issues should pertain to the engine itself and not a faulty map.
