### ISSUE TITLE
Few bugs with rchat.c and "characteristic 48 not initialized" in Q3 Demo/Demo Test, as well as weapons not looking like they should, etc.

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#232]
I happened to spot a few bugs with rchat.c and Error: characteristic 48 not initialized in the Spearmint Quake 3 Demo Test. The regular demo also has these errors, but the characteristic 48 not initialized error does not occur. It also seems the lightning gun is affected as well. It had a different shader than the final's lightning gun. It fires out the missing texture error instead of the proper lightning.
Here's the console snapshots from in-game:
![spearmint q3 demo test problem](https://cloud.githubusercontent.com/assets/17090935/15194640/458b05c2-179a-11e6-8884-efc8e6ab3791.jpg)
![spearmint q3 demo test problem 2](https://cloud.githubusercontent.com/assets/17090935/15194639/4587e414-179a-11e6-9307-b2ac1c431772.jpg)
I hope these can be fixed up. The sounds should be no problem to fix, just make a pk3 for the patch data with the necessary sounds. I already have a patch for Sarge's taunt (just couldn't be bothered to put it up). The other taunts should be just as easy to fix (before you flamewar, yes, it warns about those not present as well). Also, another bug I found for the demotest is that the skill indicators don't show up.
Here's a snapshot of this:
![shot0000](https://cloud.githubusercontent.com/assets/17090935/15198851/7c7ffa68-17b0-11e6-86d1-41831ca5a50a.png)
& also, the demo cannot find the main track for the main arenas (sonic5.wav).
Screenshot for that:
![spearmint q3 demo problem](https://cloud.githubusercontent.com/assets/17090935/15199210/e127037e-17b2-11e6-840e-06c96fb273b6.jpg)
Coltongit out.

**Comment by ensiform** [comment]
Is this for the official demo or q3test pre release?

**Comment by coltongit** [comment]
This happens to exist for both. I'll modify it as such. I think the shader LG bug also happens for the demo, as it uses a unique shader than both the demotest & the full version.

**Comment by coltongit** [comment]
I think the demo/full version's taunt files can be used for the most part to fix the taunt warnings. I have a silent taunt file for this Sarge, as it uses a different gesture than the final/demo's Sarge does, meaning using the demo/full version's taunt for that gesture essentially makes NO sense!

**Comment by mecwerks** [comment]
Im going to guess that the test version says this because it was a test version and probably didnt contain all files with it. As for the rchat.c, this is probably due to a bot characteristic being added to the engine after the test version was made. Correct me if I'm wrong but supporting non-official version of the game is something i don't believe should be a concern for spearmint. As for loading the default games assets to make the demo/test version run completely seems a little backwards doesn't it? If you have the full version running, I see no point in ensuring a test release works or even if a demo release will work. Also please think about trying to solve this stuff on your own, as it doesn't always necessarily pertain to the Spearmint engine and @zturtleman isn't here to fix every little thing you come across :P

**Comment by LavenderMoon** [comment]
I can see the point in using the final version's files to get a prototype working for historical examination, but the prototype seems to already be working. I heavily disagree with including audio files from the full Q3 release as patch files for the Q3 Demo and Prerelease, as those wouldn't be fixes so much as a mod to make the demos more inline with the final release.

I can see supporting one or more of the prototypes as being within Spearmint's scope, but I doubt there's enough interest to justify the amount of reverse-engineering and the opportunity cost of working on supporting other Q3-based games. Mind you, I'm not @zturtleman, so this is just my opinion.

**Comment by coltongit** [comment]
I'll probably try & see if pak4.pk3's rchat.c fixes the rchat.c problem for both demos.

**Comment by coltongit** [comment]
I've already fixed up a lot of these errors, the only one left is the shader error on the lightning gun. That's all there's left to fix, then I'm set!

**Comment by zturtleman** [comment]
I am aware of all of these issues. spearmint-patch-data isn't intended to introduce new game data files, but in some cases it's required for bare minimal functioning of a game (because it's not compatible with Q3 game code) and/or working around different engine behavior.

All of these issues can be fixed (i.e., disable loading taunt sounds) by changing the mint-arena mod code. It's not something I'm currently interested in developing or maintaining. The rchat.c warnings are legitimate, so I am not going to disable them in mint-arena.

One of the Q3 point releases changed the lightning gun shader used in game from lightningBlot to lightningBoltNew. I don't know if they changed how it's rendered or just the shader.

According to the [spearmint-patch-data readme](https://github.com/zturtleman/spearmint-patch-data) the only `"playable"` games of the _24 game releases_ :laughing: represented in Spearmint patch data are Quake 3 (1.32), Team Arena (1.32), and OpenArena (0.8.8). The rest are for engine testing &mdash; for my personal amusement I guess.

**Comment by coltongit** [comment]
Then I guess I can personally fix this now. Thank you for telling me what the new lightning bot shader is. I can make a pull request with a pak1.pk3 containing the missing stuff.

**Comment by zturtleman** [comment]
Non-essential game data added by demo/retail Q3 isn't going to be added to Q3 Tests' spearmint-patch-data.

**Comment by coltongit** [comment]
I COULD mirror a DL link to the patch pk3 for the patch data (I know, sounds kinda redundant now doesn't it?).

**Comment by zturtleman** [comment]
If you want to make a Q3 Demo Test mod that uses Spearmint, that's up to you. It doesn't belong in spearmint-patch-data. I'm not going to link to mods that are copyright infringement (data copied out of Q3 pk3s), this doesn't stop you from doing it though.

**Comment by coltongit** [comment]
I happen to have a new repo for this purpose called https://github.com/coltongit/spearmint-unofficial-patch-data. It has the files required for the demo/demotest to be functional.

**Comment by ensiform** [comment]
Taking files from the retail release doesn't make the demo test functional it's just stealing files from retail to work with the free version.  You're essentially trying to run q3 whatever on the game code of the full final release which is why you have the issue and the demo was only meant for the demo.

**Comment by coltongit** [comment]
Under my testing, yes, this does seem to work just fine. It's possible to even add additional bots from the full version to these, but that's just going too far at the moment.
