### ISSUE TITLE
Bots in demoq3/demoq3test not going to activate the door in q3dm7

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#243]
I just found out by playing them that both the Spearmint Quake 3 Demo as well as the demotest counterpart suffer the same issue as baseq3 once did for q3dm7 (the bots not going to activate the door like they do in baseq3). They run around on the door instead. I'm pretty sure they could, in theory, be doing the same thing there as you tested for baseq3 @zturtleman. I know what you're thinking (I just fixed the bot behavior though!!! This is just plain nuts arrggggghhhhh!!!!!!) because I'm thinking the EXACT same thing as you right now (as of 05/15/2016 @11:40 PM).

**Comment by zturtleman** [comment]
mm. The AAS was built with BSPC before platforms were stored in AAS area contents. I disabled activating entities on touch when blocked when bot_predictobstacles was enabled (it is by default) because I thought it was more logical. I've reverted the change, now bot AI can activating the door in demoq3 again. https://github.com/zturtleman/mint-arena/commit/8fce30b7997d2e5e4e3decf4c3e4a326e4e3c613.

**Comment by coltongit** [comment]
Thanks Zack. Will try it out later today.
