### ISSUE TITLE
Bots in baseq3/demoq3/demoq3test get distracted easily by other bots when going to activate q3dm7 door and get stuck in RA room

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#246]
The bots in baseq3/demoq3/demoq3test get distracted easily when they go to activate the q3dm7 door. Also, they all get stuck in the RA room once they get in the door.

**Comment by coltongit** [comment]
I'm thinking the behavior that should fix it is the fact that the bots should not go for the health balls unless they aren't at full health, which would fix the issue and allow the bots to carry on and NOT get stuck in that room.

**Comment by zturtleman** [comment]
I can confirm I have seen this as well. Though not all got stuck in the RA room.

**Comment by KuehnhammerTobias** [comment]
Only two small notes:

Be careful to not mix up various AI problems:
Please bear in mind that the latest changes to AI code (concerning the fix for q3dm7) is wrong.
Whereas it will improve the q3dm7 (door) behaviour, it will break bot behaviour on some other (custom) maps (e.g.: [Claustrophobopolis 2003](http://de.ws.q3df.org/map/nodm7/)). Thats's why we need some more common improvements. Therefore I think this issue is still the same issue as: https://github.com/zturtleman/spearmint/issues/219 and part of https://github.com/zturtleman/spearmint/issues/220.
So, all in all we know the issue and we try to solve it. 
Hmm, it would be cool to find some real intelligent solution for the bots 'puzzle logic' in general. Though, maybe fixing all maps with issues with specific bugfixes especially for those maps will be the final solution (in this case you even can use the [BotMapScripts](https://github.com/zturtleman/mint-arena/blob/master/code/game/ai_dmq3.c#L3846) function, though, this is bad (imo)).

Second, if a bot goes for health or not, is (also) decided in the botfiles (fw_items.).
In this file the various case labels represents the bots actual health, and the scale factor determines if he should go for a new health. As you can see, even if the bot health is 100 or more, he will still go for that health item (even if he can't pick it up). So bots will always go for items even if they can't pick it up.
***** FOR GOOD REASON! *****
It's on my issue tracker to improve the item-pickup behaviour [BotAI Enhancements](https://github.com/KuehnhammerTobias/ioid3-game/issues/3).
So, I think your thoughts are theoretically right, but in practice to stop bots from going for the health will lead to various other problems (e.g.: on maps with only a few items bots will tend to not find any useful items he should go for if the items didn't respawn etc.).

Well, I know this doesn't really help you much, during the latest 15 years (!) I simply noted that it is very critical to solve some AI issues found on a specific map. It is very likely that you'll break bot behaviour in other cases. :weary:

**Comment by coltongit** [comment]
Well then it's harder than I thought it would be, but that fw_items.c could be a last resort solution.

**Comment by zturtleman** [comment]
I'll look into fixing nodm7 / improve activate entity. I'm not going to change botfiles besides using GPL Q3 1.32b based inv.h for game VM compatibility.

#219 is a movement prediction error. #220 is a behavior change for when and what to do when activating an entity (though some of the linked commits are not directly related). Neither issues are directly related to selecting long term or nearby items after done activating entity, which is the cause of getting stuck in the RA room. I'm not planning to change item selection, at this time anyway.

> get distracted easily when they go to activate the q3dm7 door

This is really vague, distracted by what? Please use `devmap q3dm7; wait 500; bot_report 1; bot_shownodechanges 1; addbot Sarge; 2dropin; 2follow Sarge` when testing this issue to be sure you're not making false assumptions about what the bot is doing. For example, if the console says `from activate: time out` then the bot wasn't distracted at that moment, it just took too long to complete it (bot is hard coded to give up after 10 seconds).

**Comment by coltongit** [comment]
They get distracted by other bots in the same room as the door at the same time.

**Comment by zturtleman** [comment]
The bot's primary goal is to kill other players.
