### ISSUE TITLE
I happen to have the full version of Q3Test 1.07

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#252]
As I explained in #250, I happen to have the full version of Q3Test 1.07. Here's the link to it if you missed it: https://mega.nz/#!1kEmFR5Z!rfIvenHDLxu8Ms1j9WaN_zWJ7iXYsQRrh6e71U9Fb8c

**Comment by KuehnhammerTobias** [comment]
Why do you push an issue by creating a new ticket? Moreover what is the issue here? You do offer something, right?
Could be something for the new forums? Check it out: http://chat.clover.moe/.
Well,  I'm not Zack, so he will decide, but I suggest to keep the Spearmint issue tracker a bit more 'structured', others might participate and refer to Spearmint's issue tracker as well.
No offense! Just a suggestion.

**Comment by coltongit** [comment]
Thanks for the heads up, @KuehnhammerTobias.
