### ISSUE TITLE
Game doesn't save progress for q3dm0

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#254]
The game isn't able to save the progress for q3dm0, thus you can never move past Tier 0 in terms of levels unlocked. It ACTS like you've unlocked the next tier, though. That's the reason why `iamacheater` still works. This happens in the latest git, & possibly Spearmint 0.3.
Here's why it happens: the game doesn't update the level unlock info when unlocking Tier 1 from Tier 0. Tiers 2-7 still work however for whatever reason. I beat q3dm0 on a higher level than I Can Win, but the level info when I go to it still says I beat it at I Can Win.

**Comment by zturtleman** [comment]
works for me. what are the contents of g_spScores1 to 5 cvars? do you have additional single player maps?

**Comment by KuehnhammerTobias** [comment]
This works for me too. There is no difference to vanilla Q3 or ioquake3, in this case.

Iirc a very looooong time ago, I had some similar problems, can't remember exactly but I think my config file was write-protected. Hmm, eventually check if your cfg is accessible. At least on Windows the cfg storing is awful, especially if you have many games installed.
And be careful wen copying/deleting pak into/from your Spearmint installation and modifying your mint-game setting or modifying home/game path.
From time to time I am (was) able to load a wrong pk3 from a different path! That's why Zack modified/corrected the game-settings behaviour iirc. On the other hand, I still assume careless users can f*** this up. Though, I'm currently NOT able to reproduce this issue of loading the wrong pk3.
So eventually always check twice if Spearmint loads the correct pk3, and uses correct mint-settings and cfg!
I have no idea what else could be wrong.

**Comment by coltongit** [comment]
I have found out that this happens on the last level of every tier, it doesn't unlock the next one because of this bug. I downloaded 0.3 on another computer & it worked fine, so what's going on here?

**Comment by zturtleman** [comment]
I really don't know. Check that `which config.cfg` console command gives file in fs_homepath and that the Windows file properties for it has read/write permissions. I think if you put Spearmint in C:\Program Files\ and use the "settings" directory homepath there might be issues of not being able to write config.cfg.

**Comment by coltongit** [comment]
I put it on a flash drive and used <flash drive letter>:/<spearmint path>, with a batch file to make the engine use the pk3s from another spearmint. P.S. they are both from git source.

**Comment by coltongit** [comment]
Using a fresh 0.3 on my main computer works fine. q3dm0 saves with no problems. P.S. the problem Spearmint can access the config fine, I can access it fine also. So no problems there...

**Comment by zturtleman** [comment]
This doesn't appear to be caused by Spearmint.
