### ISSUE TITLE
Allow mouse wheel & next/previous weapon controller/keyboard buttons to scroll to the gauntlet

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#257]
Another annoying thing with the game is why you have to use an extra button for the gauntlet? I think it should be possible to just allow the mouse wheel/controller/keyboard buttons for next/previous weapon also be usable for the gauntlet as well.

**Comment by LavenderMoon** [comment]
Having it as an option in the controls menu would be nice.

**Comment by mecwerks** [comment]
I don't think this is something that is in the scope of spearmint. This is how it is in original quake 3. It's also a personal preference to have it like you want it.

**Comment by KuehnhammerTobias** [comment]
Yes, I agree with mecwerks. Moreover if you find it annoying to press a key to switch to gauntlet, than you didn't play Q3 excessively.
Consider buttons as 'fast access'! You can backstab players etc. So this is an essential gameplay 'feature'. Have a look at other games, like Enemy Territory, there the classes have special keys for their class specific tools (syring, etc.).
So, something that is annoying to you, isn't automatically annoying to others.
The idea of LavenderMoon seems okay, though.

**Comment by coltongit** [comment]
I agree. Having an option for this in the options menu would be awesome.

**Comment by zturtleman** [comment]
I agree it's odd Gauntlet skipped in the weapon cycle.

Though, when you're like "Crap this gun isn't working out! What else do I have???" Gauntlet _probably isn't_ what you want. I would think a player would explicitly know they want the Gauntlet. So when they don't want it, cycling to it just wastes time and button presses for keyboard / gamepad. If a player wants the Gauntlet there is a good chance they want it _now_, so it would be better to switch to it directly. Though I'm not sure if the game should dictate this "user behavior optimization". (Which I may not have assumed correctly.)

What part of the user experience are you trying to improve by changing this? Why do you not want a button just for the Gauntlet?

I think dual analogue sticks + d-pad + 10 button controllers have enough buttons to give Gauntlet it's own button or d-pad direction. Seems like a mouse with scroll wheel and five buttons could bind it for easy access there as well.

I think instead of cycling to Gauntlet I would like a `weapontoggle 1` command to toggle between Gauntlet and gun I previously held, bound to a mouse side button (MOUSE4) or gamepad d-pad. So I can pull out the Gauntlet to try to frag a player and then switch back to what gun I was using before (without using number keys, or cycling through like half of the weapons or twice around using mouse wheel). :facepunch:

I'm not entirely opposed to adding a cvar option to allow selecting Gauntlet, but.. that means acknowledging that it's a good idea for players to do, which I'm not entirely sure is true. Might need it for Dreamcast controller support though. :suspect: 

I haven't decided anything. Here is a [patch](https://gist.github.com/zturtleman/635f6a7995d7931201aaf3c7423936dc) if anyone wants to try weapon cycle with Gauntlet or toggling between Gauntlet and gun.

**Comment by ensiform** [comment]
This is the behavior of it in q3 or no?  It certainly is the behavior in QL.

**Comment by coltongit** [comment]
You mean I have to use IPS for this?! How do I use this patch anyway?

**Comment by ensiform** [comment]
It would automatically scroll to gauntlet of you're out because the out of ammo switch doesn't use the same check.

**Comment by coltongit** [comment]
I already know that, @ensiform.

**Comment by coltongit** [comment]
@zturtleman, I fixed the "never scroll to gauntlet" comments in the patch code, here's the page:
https://gist.github.com/coltongit/cb8a53d7c5fff67d9b9d062e9c01fbeb/revisions

**Comment by coltongit** [comment]
Actually, @zturtleman, the ultimate fix for this is to determine which behavior you want in the options menu (either have a button to switch to the gauntlet then back again, OR have the mouse wheel cycle to the gauntlet).

**Comment by zturtleman** [comment]
This is Q3 behavior.

`cd mint-arena ; patch -p1 -i mint-arena_weaponToggle-and-cg_gauntletCycle.patch`

Or instead of scrolling to Gauntlet when low on ammo you could press the Gauntlet button.

After `weaponToggle 1` if you want to use a different weapon than the one you previously had, you can use the number keys to switch to a weapon directly or use next/previous weapon keys to change to next or previous weapon relative to the Gauntlet. There is still room for improve to weaponToggle. I just thought it up and coded it today.

Forking the patch to remove those comments is absolutely no help.

Actually, the ultimate fix is to leave this alone because it has worked fine for 17 years. The alternate Gauntlet selection modes are not mutually exclusive and weaponToggle shouldn't silently replace the Gauntlet select bind. So the option you suggest does not make sense to me. I think "Toggle Gauntlet" as a new bindable action in the controls menu is easy enough to understand. I still have no idea what a short understand radio button name for "select [or ignore/skip] Gauntlet in next/prev weapon" is. "Cycle to Gauntlet" is rather unspecific as to what on earth it means and no clear how to test the behavior change either.

**Comment by coltongit** [comment]
What I meant when I said that was "Cycle to Gauntlet _via mouse wheel/next/prev buttons_", which _does_ make quite a bit of sense @zturtleman.

**Comment by zturtleman** [comment]
It might be just a little too long though.

![shot0062](https://cloud.githubusercontent.com/assets/405505/15630241/4ac2d514-24f7-11e6-875d-f2426c1b9d6c.png)

**Comment by coltongit** [comment]
I think "Cycle to Gauntlet using wheel/buttons" might be better @zturtleman.

**Comment by LavenderMoon** [comment]
You could call the option "cycle past gauntlet" and have it default on. That would be only one character longer than "autoswitch weapons".

> maybe you could also make the panels (like that one) use the whole screen instead of a 4:3 area.

That wouldn't help if the player has a 4:3 or 5:4 screen. A better idea would be to use a proportional font, but that doesn't really seem necessary in this case.

**Comment by coltongit** [comment]
I agree with that @LavenderMoon.

**Comment by coltongit** [comment]
I tried to apply the patch, but the command doesn't seem to work for me.

**Comment by zturtleman** [comment]
"I tried to make a sandwich using your recipe, but it doesn't seem to work for me." You've given me nothing to be be able to help solve the issue (which is probably on your end, not the sandwich recipe). Don't depend on me being psychic please. I don't like playing 20 questions either; you usually don't answer my questions. This leaves me just trying to think of every possible issue and trying to provide how to avoid all of them. Download the patch file into mint-arena if you don't have it. Other issue, either figure it out yourself or give actual information like terminal output of patch command.

**Comment by coltongit** [comment]
I already have it inside mint-arena. Cygwin gives me command not found when I try to patch mint-arena with your patch @zturtleman.

**Comment by KuehnhammerTobias** [comment]
@coltongit: Sorry, zturtleman!....**?**... Thank you, zturtleman!....**?**
Patch mint-arena with Cygwin?

**Comment by coltongit** [comment]
Excuse me while I go get ips...

**Comment by KuehnhammerTobias** [comment]
You don't need a 'patcher'. I already pointed you to Github help pages here: [Magical Clover](http://chat.clover.moe/t/next-tier-wont-unlock-for-me-in-spearmint/27/19).
Additionally I heard of so called  [web search engines](https://en.wikipedia.org/wiki/Web_search_engine). You can search for something like: " git how to apply patches" or something...

**Comment by coltongit** [comment]
I do that and it gives me "corrupt patch at line 140".

**Comment by zturtleman** [comment]
mm, sorry about that. When I copied and pasted the patch into gist.github.com it lost the newline at the end of the file (line 140) for some reason. [Fixed in revision 3](https://gist.github.com/zturtleman/635f6a7995d7931201aaf3c7423936dc).

> What patcher supports .patch anyway?

[`patch` command](https://en.wikipedia.org/wiki/Patch_(Unix)) doesn't care what the extension is. Maybe .diff is more common. `patch` command can be [installed using Cygwin setup](https://cygwin.com/ml/cygwin/2003-05/msg00897.html).

**Comment by coltongit** [comment]
As I thought, I didn't have that installed. I installed that command & it patched OK. Thanks @zturtleman  & @KuehnhammerTobias for your help!

**Comment by zturtleman** [comment]
Added option to cycle to gauntlet: https://github.com/zturtleman/mint-arena/commit/32567b15206a24bbdc5b807589ced4177724b309
Added weaponToggle command: https://github.com/zturtleman/mint-arena/commit/41d80837b38c5352d2e6c7801da98e163c3dc140
