### ISSUE TITLE
Glass doesn't look right in dc_map01

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#264]
The glass in dc_map01 is supposed to be clear. In Spearmint (& possibly ioquake3 too), it shows up as a deep blue-green color.
Here's what I mean: 
![shot0000](https://cloud.githubusercontent.com/assets/17090935/15834037/ccf8c368-2bff-11e6-88c7-55fde7543c1e.png)
Here's what it's supposed to look like:
![shot0000](https://cloud.githubusercontent.com/assets/17090935/15834479/11028fc4-2c02-11e6-9215-02083ae681be.png)
I got the glass to show with my version of the DC mappack. With ss_maps.pk3, it simply shows as black (& has a lot of conflicting textures/shaders with a regular install).
Here's my version of the dc-mappack (all conflicting textures/shaders have been removed, & it also has the Q3TA jumppad shader conflict patch at LvL built in (what happens is the shader normally used for the jumppads in the TA maps is replaced with the one from the DC mappack, but lucky us it doesn't happen anymore)): https://mega.nz/#!04NSQB6A!qmtCyS2cnx5xS8XO6lJnYv8I8IUhLNmEAn4pzJ6-pbo

**Comment by coltongit** [comment]
Also, it seems that on the edges of the screen, the image displayed on screen seems to be distorted (it gets distorted lengthwise).

**Comment by KuehnhammerTobias** [comment]
Sorry, but what exactly should we fix here? Shaders? Bot chat?

**Comment by coltongit** [comment]
It's still a WIP with the botfiles @KuehnhammerTobias, but everything else is as it'll be in the final (I'll have the bots go to more places than they could in the original mappack).

**Comment by zturtleman** [comment]
Maybe this fixes the glass being deep blue-green? 9cec7e9e8977fd5b792670b2c5b66bb4fd49031b

Regarding distorted image, do you mean the levelshot when the map loads? The levelshot is intentionally distorted. It use to be aspect correct at one point with black edges, but I switched it back to stretched because I didn't like how it looked. I recently tested [a map](http://lvlworld.com/review/La%20Petite) that has a widescreen levelshot. I think it's best to just leave levelshot stretched to window size like in vanilla Q3 and ioquake3. As far as I know, everything else is aspect correct in widescreen.

baseq3/pak4.pk3:/botfiles/rnd.c is missing semicolons in `substance` list causing those three items to be concatenated as a single item by the [C preprocessor](https://en.wikipedia.org/wiki/C_preprocessor) used by the botlib. Fixing Q3's botfiles is outside of the scope of Spearmint; mainly because of the [license](https://ioquake3.org/extras/patch-data/).

**Comment by coltongit** [comment]
I mean the edges of the widescreen screenshot @zturtleman (take a look at the portal).

**Comment by zturtleman** [comment]
This is called [perspective distortion](https://en.wikipedia.org/wiki/Perspective_distortion_(photography)). It was reported at https://github.com/zturtleman/spearmint/issues/210. For additional information as to how perspective distortion applies to FPS games: [Field of View at Valve Developer Community](https://developer.valvesoftware.com/wiki/Field_of_View).

You can mess with these console variables, but there isn't really a way to fix it.
`cg_fovAspectAdjust 0` : disables expanding/shrinking the horizontal field of view when viewport is not 4:3.
`cg_fov 75` : decrease wide angle extension distortion.

**Comment by coltongit** [comment]
That sucks @zturtleman. Wish you know _how_?

**Comment by KuehnhammerTobias** [comment]
@coltongit: Additionally eventually cg_splitviewVertical will help to fix the distorted image, what are your settings?: https://forum.clover.moe/t/splitscreen-fov-field-of-view/35
:)

**Comment by coltongit** [comment]
dc_map01 glass is looking fine now @zturtleman. It's clear again. Closing this because of it.
