### ISSUE TITLE
Implement a selective shader system for Spearmint

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#266]
This type of shader system would solve shader conflicts for good in most maps (like for example, the Sega DC mappack's dc_map24 & Q3TA's mptourney2). What it would do is use one shader when a specific map is loaded, then switch back to the other one when the other map loads. It should also be usable with ioquake3 as well as legacy Q3A if possible. I think this would be a good solution, wouldn't it, @zturtleman?

**Comment by Razish** [comment]
If I'm understanding you correctly, the better option would be for content creators to stop creating broken content.
It's not the programmer's job to introduce content-specific hacks for something that should instead be fixed by the infringing content.

If the map is broken, the map is broken. The only acceptable solution is to make a non-broken map.

**Comment by coltongit** [comment]
Don't blame me on this one. id Software was the one who introduced the shader conflicts between those 2 maps, not me.

**Comment by Pokemoon** [comment]
Were these shader conflicts in the original DC version of Quake 3, or did they only come up when paired with the PC version's content? Either way, if you're the one curating this map pack, then you are now effectively the map designer. Fix the map to work correctly on modern engines. You should be able to rename the shaders and change the references to them, if my understanding of Quake 3 is correct.

**Comment by coltongit** [comment]
It also required a hexedit of the affected texture directories @Raz0r.
