### ISSUE TITLE
Team Arena (& the Team Arena demo) no longer work with the Spearmint patch data

### ISSUE THREAD

**Issue by coltongit** [zturtleman/spearmint#268]
Both Quake 3 Team Arena and the Q3TA demo don't seem to work at the moment with the Spearmint patch data (and the full Team Arena is using the wrong menu logo as well, it should be using the same menu logo as the demo). All it gives me is the Quake 3 menu with the Team Arena font & cursor sound. It also uses the Q3TA console shader as well.

**Comment by coltongit** [comment]
I'm also using the Q3TA unofficial patch with Spearmint.

**Comment by zturtleman** [comment]
Team Arena using Spearmint 0.3 works for me. It sounds like it's loading the baseq3 mint-cgame instead of the missionpack mint-cgame (the files are different). `vminfo` command will tell where the VM is loaded from (which helps if it's not picking the file you expect).

Team Arena is using the loading screen that I want. The Team Arena demo is missing the Q3 menu background, so I had to use a different one.

**Comment by coltongit** [comment]
That must be the case. I'll go compile them both then.

**Comment by coltongit** [comment]
Welp, that one's fixed. Closing...
