### ISSUE TITLE
dedicated server app crashes on startup.

### ISSUE THREAD

**Issue by Caseylee6** [zturtleman/spearmint#277]
title says it all, trying to start a dedicated server for my pals and whenever I start the server program (both 32 bit and 64 bit) they both crash right when I start them. downloaded from binary, ive tried the binary for .4 and .3 and both crash on startup. I am running windows 10 64 bit, any help on the issue would be appreciated. thank you!

here is a recording of my issue
https://youtu.be/YyeCKw2VUCs

**Comment by zturtleman** [comment]
Hmm, this is a problem with the development code as well. I'll look into it.

**Comment by zturtleman** [comment]
Spearmint 0.4 and earlier print a message before the Windows console is initialized (`Con_Init()` function) which may result in the command prompt crashing. Based on limited testing the crash seems to have been introduced by a Windows 10 update -- possibly the Windows 10 Creators Update.

The above issue has was fixed in ioquake3 and merged into Spearmint recently by calling `Con_Init()` earlier in the start up process. However, this unexpectedly resulted in Spearmint crashing on all Windows versions due to the game title for the console window not being initialized yet. This is now fixed in https://github.com/zturtleman/spearmint/commit/914ef509fc24e591586996bcbcf847f461254713.

Thanks. Here are fixed Spearmint 0.4 Windows server executables based on the latest development code: http://clover.moe/downloads/spearmint-server-0.4-20170820.zip
