### ISSUE TITLE
Can't load Distant Screams (mpterra2)

### ISSUE THREAD

**Issue by xesarni** [zturtleman/spearmint#280]
Loading crash:
> Client Shutdown (Client fatal crashed: Z_Malloc: failed on allocation of 6363176 bytes from the Game VM zone)

spearmint-0.5

**Comment by zturtleman** [comment]
After starting Team Arena open the console using ~ or shift+escape and type "vm_gameHeapMegs 24" and press enter. This will change the Game VM dynamic memory pool size to 24 megabytes instead of the default 8.

The Game VM dynamic memory is allocated in the engine hunk memory (size controlled by com_hunkMegs cvar) so this just changes where memory is available without increasing the overall memory usage. The additional usage that causes this error is probably the result of moving the botlib and AAS file loading from the engine into the Game VM in Spearmint 0.5.

The default vm_gameHeapMegs size is increased to 24 in 1d1a55ba70ec979ea0e2bab1a37424dc3be2950a and will be the new default in the next release. Thanks.
