### ISSUE TITLE
Some cfg commands don't seem to work

### ISSUE THREAD

**Issue by Riccardoman** [zturtleman/spearmint#319]
seta cg_kickScale "0"
seta cg_ScreenDamageAlpha "0"
seta cg_ScreenDamageAlpha_Team "0"

**Comment by KuehnhammerTobias** [comment]
Hi, those cvars aren't working because they simply do not exist.
Since you are talking about game cvars (not engine cvars), here are the cvars that do exist for mint-arena: https://github.com/zturtleman/mint-arena/blob/master/code/cgame/cg_local.h#L1321
Note, 'cg' named cvars are refering to the cgame module and NOT the Spearmint engine.

**Comment by zturtleman** [comment]
`com_blood 0` will disable screen damage blood (and all other blood effects). I don't think there is a way to disable damage kick.

**Comment by KuehnhammerTobias** [comment]
Yeah, wasn't there a gentity flag or something like FL_NO_KNOCKBACK or so? Iirc this was also disabling damage kick, correct me if I'm wrong. I think I didn't even test those flags.

**Comment by zturtleman** [comment]
FL_NO_KNOCKBACK disables moving entity when hit or such. cg_kickScale would probably be implemented [here](https://github.com/zturtleman/mint-arena/blob/9ffc594a3d15e942ed19f0203d8724b10dff14f9/code/cgame/cg_playerstate.c#L126) by `kick *= cg_kickScale.value;` — just guessing from cvar name.
